### ISSUE TITLE
[Question] Is MR RR or Yale

### ISSUE THREAD

**Issue by loretoparisi** [cheunghy/kroman-js#2]
Which romanization table has been used? Thanks.

**Comment by victorteokw** [comment]
Hi @loretoparisi, kroman.js doesn't use any romanization table.

**Comment by loretoparisi** [comment]
@zhangkaiyulw thanks, so which romanization is used?

**Comment by victorteokw** [comment]
Hi @loretoparisi kroman uses internal pattern of UTF8 encoding. 
See code here https://github.com/zhangkaiyulw/kroman-js/blob/master/kroman.js

**Comment by loretoparisi** [comment]
thanks!
